image: sickcodes/docker-osx:naked

stages:
  - test

Test Arbitrage Server:
  stage: test
  script:
    - cd arbitrage-bot
    - xcodebuild test -scheme Arbitrage\ Bot -project Arbitrage-Bot.xcodeproj/
